<?php

const COMMERCE_UTM_TAGS = 'drupal_commerce_utm_tags';

/**
 * Implements hook_boot().
 */
function commerce_utm_boot() {
  if (!isset($_SESSION[COMMERCE_UTM_TAGS])) {
    // Save incoming UTM tags.
    $tags = array();
    foreach ($_GET as $name => $value) {
      if (strpos($name, 'utm_') === 0) {
        $tags[$name] = $value;
      }
    }
    $_SESSION[COMMERCE_UTM_TAGS] = json_encode($tags);
  }
}

/**
 * Implements hook_commerce_order_presave().
 */
function commerce_utm_commerce_order_presave($order) {
  if ($utm_field_name = variable_get('commerce_utm_field', NULL)) {
    if (!empty($_SESSION[COMMERCE_UTM_TAGS])) {
      $order_wrapper = entity_metadata_wrapper('commerce_order', $order);
      if (!$order_wrapper->{$utm_field_name}->value()) {
        // Move tags from session into order field.
        $order_wrapper->{$utm_field_name} = $_SESSION[COMMERCE_UTM_TAGS];
        unset($_SESSION[COMMERCE_UTM_TAGS]);
      }
    }
  }
}
